# Generated by Django 4.0.4 on 2022-05-13 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [ ('tirociniApp', '0001_initial'),]

    operations = [
        migrations.AlterField(
            model_name='richiesta',
            name='autocertificazione',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='stato',
            field=models.IntegerField(choices=[(0, 'Richiesta non ancora visionata'), (1, 'Richiesta approvata')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Professore'}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
