# Generated by Django 4.0.4 on 2022-06-23 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tirociniApp', '0004_studente_delete_professore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studente',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='studente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studente',
            name='nome',
        ),
        migrations.AddField(
            model_name='studente',
            name='user',
            field=models.OneToOneField( on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='studente',
            field=models.ForeignKey( on_delete=django.db.models.deletion.DO_NOTHING, to='tirociniApp.studente', null=True),
        ),
    ]
