# Generated by Django 4.0.5 on 2022-07-21 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tirociniApp', '0006_alter_richiesta_durata_alter_richiesta_studente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiesta',
            name='studente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tirociniApp.studente'),
        ),
        migrations.AlterField(
            model_name='studente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
