# Generated by Django 4.0.5 on 2022-07-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tirociniApp', '0010_alter_richiesta_studente_alter_studente_matricola'),
    ]

    operations = [
        migrations.AddField(
            model_name='studente',
            name='corso',
            field=models.CharField(default=-192, max_length=6),
            preserve_default=False,
        ),
    ]
