# Generated by Django 4.0.5 on 2022-07-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tirociniApp', '0011_studente_corso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studente',
            name='corso',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
