# Generated by Django 4.0.5 on 2022-08-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tirociniApp', '0012_alter_studente_corso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiesta',
            name='stato',
            field=models.IntegerField(choices=[(0, 'Richiesta non ancora visionata'), (1, 'Richiesta approvata'), (-1, 'Richiesta rifiutata')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='studente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tirociniApp.studente'),
        ),
    ]
