# Generated by Django 4.0.5 on 2022-10-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tirociniApp', '0015_corso_tipo_alter_corso_durata_tirocinio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studente',
            name='corso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tirociniApp.corso'),
        ),
    ]
