# Generated by Django 4.0.5 on 2022-10-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tirociniApp', '0016_alter_studente_corso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studente',
            name='classe',
        ),
        migrations.AddField(
            model_name='richiesta',
            name='corso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tirociniApp.corso'),
            preserve_default=False,
        ),
    ]
