# Generated by Django 4.0.5 on 2022-10-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tirociniApp', '0017_remove_studente_classe_richiesta_corso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiesta',
            name='studente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tirociniApp.studente'),
        ),
    ]
